Feature/add color generator
togostanza/metastanza pull request #107
Opened 2022-06-03 07:23 UTC by gstein314

グラデーションを追加しました。お手すきの際にご確認ください。

2022-06-17 08:31 UTC, gstein314 commented
@penqe 
お疲れ様です。circulateとinterpolateのクラスを追加しました。
お手すきの際にご確認ください。

2022-06-17 08:41 UTC, penqe requested changes
見ているコードが古いようです。

2022-06-17 08:41 UTC, penqe commented on lib/ColorGenerator.js
> +  constructor(range, domain) {
@gstein314 古いままのようです。
見ているものが違う？

2022-06-17 10:21 UTC, gstein314 commented
@penqe 
lint errorでpushできていなかったようです。修正してみました。

2022-06-19 07:09 UTC, penqe approved these changes
コードにはいろいろ注文をつけていますが、機能的には問題ないように思うし、差し当たって私も使いたいので、一旦マージします。改めて修正してください。
スタンザのコードは、テスト用ということもあり、あまりチェックしていません。ですがこちらもある程度のブラッシュアップは必要かもしれません。

全体として感じたことです。
- コメントをつけてください。
- ケアレスミスというか、無意味なコードが紛れ込んでいるようです（ペアプロで指摘したもの含め）。まずはこういったことに自分で気付けるようになってください。
- 美しい（合理的な）コードを書く、という意識がないようです。自分もとりあえず動けば良いという書き方ですが、プルリク出す段では推敲するようにしてください。

2022-06-19 07:10 UTC, merged