Feature/dendrogram d3
togostanza/metastanza pull request #109
Opened 2022-06-22 07:30 UTC by YukikoNoda

以下の修正を行いました。
- ToolTip機能の追加
- ハードコードをparamsで変更できるように機能変更
- グラフの傾きをもともとあるTreeを参考に調整

2022-06-29 06:12 UTC, YukikoNoda commented
dendrogramを作成しました。ご確認をお願いします。
- ノードの深さごとに色を変更しています。
- ノードをクリックすることで、開閉操作を行うことができます。
- ノードをホバーするとToolTipが表示されます。


<img width="486" alt="dendrogram" src="https://user-images.githubusercontent.com/47429234/176363865-7a36c181-b201-4530-b3b8-9ca379de7c8a.png">

2022-07-04 06:57 UTC, penqe requested changes

2022-07-04 06:57 UTC, penqe commented on stanzas/dendrogram-d3/index.js
> +    const togostanzaColors = [];
これでも問題ないのですが、行事さんがライブラリを作ってくれたので、そちらを使ってもらえれば。
```
import {
  getColorSeries,
} from "@/lib/ColorGenerator";
...
const togostanzaColors = getColorSeries(this);
```

2022-07-04 06:57 UTC, penqe commented on stanzas/dendrogram-d3/index.js
> +    const existingSvg = root.getElementsByTagName("svg")[0];
これは、パラメータ変えた時とかに複数生成されるのを防ぐためですか？

2022-07-04 06:57 UTC, penqe commented on stanzas/dendrogram-d3/index.js
> +        .attr("transform", "translate(" + source.y0 + "," + source.x0 + ")")
これもこのままで良いですが、Template literal を使うのが今時かもですね。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Template_literals

2022-07-04 08:23 UTC, YukikoNoda commented
グラフを末端を揃えるclusterと、揃えないtreeタイプで切替可能としました。
デフォルトがtreeです。
params名はgraph-typeとしました。

2022-07-04 08:38 UTC, YukikoNoda commented on stanzas/dendrogram-d3/index.js
> +    const togostanzaColors = [];
現在のブランチにColorGeneratorのライブラリがないため、merge後に追加いたします。

2022-07-04 08:56 UTC, YukikoNoda commented on stanzas/dendrogram-d3/index.js
> +    const existingSvg = root.getElementsByTagName("svg")[0];
そうです。新しいsvgが追加されてしまうのを防ぐためです。

2022-07-05 00:44 UTC, penqe commented on stanzas/dendrogram-d3/index.js
> +    const existingSvg = root.getElementsByTagName("svg")[0];
あの画面の不具合なので、この処理は不要です。

2022-07-05 00:46 UTC, penqe requested changes
svg重複解決の処理は、削除してください。
ヘルプ画面の不具合なので、こちらでの対応は不要です。

2022-07-05 04:30 UTC, YukikoNoda reviewed
以下3点の修正を行いました。
- getColorSeriesの使用
- translateをTemplate literalを使用して書き換え
- svg重複解決の処理の削除

2022-07-05 04:32 UTC, penqe approved these changes
ありがとうございます

2022-07-05 04:32 UTC, merged