Feature/dendrogram d3
togostanza/metastanza pull request #112
Opened 2022-07-07 01:13 UTC by YukikoNoda

データ自体にcolor というkey があったら、その色を使うようにする機能を追加しました。

2022-07-07 04:49 UTC, YukikoNoda reviewed
Zoom機能を追加しました。
zoomの可否をparamsで受け取ること、幅、高さ、可動域の設定は今後行う予定です。

2022-07-07 04:51 UTC, YukikoNoda reviewed
グラフの向きを変更可能にしました。
ただし、グラフの向きを変更した場合paramsのheight,widthがテレコになってしまうため、修正が必要です。

2022-07-07 10:12 UTC, YukikoNoda reviewed
zooming機能の最大と最小拡大率、最大の可動域の設定を行いました。

2022-07-07 10:23 UTC, YukikoNoda reviewed
zooming機能可否のparamsを追加しました。
paramsの名前がわかりにくいと思うので指摘をいただけると嬉しいです。

グラフ全体の大きさに相対の場合はZoom機能ナシ、nodeSizeに対し絶対の場合にzooming機能の付与を行おうと考えています。
詳しくは[ClickUP](https://app.clickup.com/t/2t2m5uy)に書いております。

2022-07-11 04:39 UTC, YukikoNoda reviewed
nodeサイズの表示の可否を変更できるようにしました。
サイズ名、サイズのscaleもparamsで受け取れるようにしています。

jsonのparamsの説明文などわかりにくい部分があるかもしれないので、ご確認をお願いいたします。

2022-07-11 05:47 UTC, YukikoNoda reviewed
グラフの向きを切り替える際に、テキストも縦、横に切り替わるようにしました。
また、縦、横の名前をhorizontalとverticalに変更しました。

2022-07-12 01:31 UTC, neznayer commented on stanzas/dendrogram-d3/index.js
> +        );
`.attr("r", d => ..... )` は、全てのdataを一個一個 (`d`) を見ていくのですが、
さらに、その中に　`data.some` で全てのデータの一個一個をチェックすると、O(n^2) の難しさになってしまいそう。（データの数が　２倍上がった場合、イテレーションの数は　４倍上がる）

`.attr("r", d => ..... )`　の部分のどこか前に`some`を１っかいだけ確認したらOKなはずです。

2022-07-12 03:02 UTC, YukikoNoda reviewed
nodeSizeに対し絶対の場合の描画位置を中央に変更しました。
現時点でのZoomに関することの実装は以上になります。

実装内容は[ClickUP](https://app.clickup.com/t/2t2m5uy)をご確認ください。

2022-07-12 10:15 UTC, neznayer commented on stanzas/dendrogram-d3/index.js
> +
@YukikoNoda お疲れ様です。ありがとうございます！ 👍

2022-07-12 10:25 UTC, neznayer commented on stanzas/dendrogram-d3/index.js
> +
@YukikoNoda ありがとうございます！　🙇‍♂️

2022-07-12 10:37 UTC, YukikoNoda reviewed
グラフの描写を曲線と直線で切替可能にしました。
しかし、attr内の属性値を4つの分岐で切り替える方法が思いつかず、if文で切り替えているので大変長くなっております。`.transition()`, `.duration(duration)`はそれぞれの分岐で記入しなければ、反映されない状態です。

また、グラフの描写を先日お伝えした方法とは異なり、topから描くのではなく、centerから描いています。
※曲線との切替を容易にするためにそうしました。

ご確認をお願いいたします。
![スクリーンショット 2022-07-12 19 35 43](https://user-images.githubusercontent.com/47429234/178471571-ba7d58d2-45bc-498e-ac59-e08cce578e64.png)

2022-07-13 00:52 UTC, YukikoNoda reviewed
paramsの名前を`graph-display_mode`[`fix node size`, `fix graph size`]に変更しました。

2022-07-13 02:34 UTC, YukikoNoda reviewed
@neznayer Zoom機能がなく、グラフがverticalの際に、グラフが欠けてしまうことを全体のsvgのwidth, heightを入れ替えることによって修正しました。

しかしそのため、vertical時のparamsの入力時にwidth, heightがテレコで入力になっております。この解決方法で良いのか疑問が残るので、ご確認をお願いします。

2022-07-13 08:38 UTC, YukikoNoda reviewed
pathの描画を三項演算子をネストし4分岐にしました。
これによりバグも解消されました。

2022-07-13 09:01 UTC, YukikoNoda reviewed
verticalでグラフを描いたときにnodesizeを変更することで、グラフ全体を表示できるようにしました。

2022-07-13 09:28 UTC, YukikoNoda reviewed
`node-color-data_key`を追加し、keyを受け取ることにしました。

2022-07-14 02:06 UTC, neznayer requested changes
@YukikoNoda  ありがとうございます！

細かいですけれども、`straight`の`vertical` の時、リンクがこんなふうになっているのですが、
![image](https://user-images.githubusercontent.com/55772081/178880580-976630c6-422a-4498-9639-ff8984b77420.png)
（水平・垂直・水平）
`vertical`の場合は (垂直・水平・垂直) が必要になりますね。。
<img width="888" alt="image" src="https://user-images.githubusercontent.com/55772081/178882359-3511d30a-8e04-4f37-b6c9-cc764bdf07f1.png">

2022-07-14 08:04 UTC, YukikoNoda reviewed
直線pathかつvertical時のpathの描き方を変更しました。
pathに関する条件文のネストが一段深くなりました。

また現在、直線pathの場合d3.curveStepで描いていたとしても、線の重複により部分的に濃く見えてしまいます。

2022-07-14 08:20 UTC, YukikoNoda commented
`graph-display_mode`を`fix graph size`にするとずれてしまうので調整します。
また、ToolTipsがホバーしても表示されない場所があるので、原因を探します。

2022-07-14 08:43 UTC, YukikoNoda reviewed
直線pathがvertical時に、`graph-display_mode`を`fix graph size`にしたときのズレを解消しました。

2022-07-14 08:47 UTC, YukikoNoda commented
pathが曲線または直線 かつ `vertical`表示 かつ `graph-display_mode`が`fix graph size`時にデフォルトの表示位置が中央でないため修正を行います。

2022-07-15 02:11 UTC, YukikoNoda reviewed
pathが曲線または直線 かつ `vertical`表示 かつ `graph-display_mode`が`fix graph size`時にデフォルトの表示位置が中央でない件を修正しました。

分岐が更に深くなってしまいました。

2022-07-15 02:25 UTC, YukikoNoda reviewed
グラフの描画の始点位置を`graph-display_mode`によって分岐させました。

2022-07-15 08:46 UTC, YukikoNoda reviewed
以下の修正を行いました。
- nodeSizeで描画した際のcircleの配置方法
- Zoomを行う際の可動域
- Y軸のユーザー指定marginの追加

paramsを`user-y-margin`、デフォルトの値を0、説明文を`Y margin in px`としました。
ご確認をお願いいたします。

2022-07-15 08:47 UTC, YukikoNoda reviewed
`graph-display_mode`のparamsの値を逆にしました。

2022-07-20 02:16 UTC, YukikoNoda reviewed
params`graph-display_mode`を`graph-fit_to_size`に変更。
また、わかりやすくするためにbooleanにしました。

2022-07-20 02:21 UTC, YukikoNoda reviewed
nodeのcircleに関して以下の変更
- keyを`node-size-fixed_size`から`node-size-default`に変更
- descriptionの変更。適応条件の追加
- 直径から半径を受け取ることに変更
- 半径を受け取ることによるindex.jsの変更
　※ただし、これはユーザー指定にするためparamsを追加するか検討中

2022-07-20 02:36 UTC, YukikoNoda reviewed
`graph-type`を`graph-align_leaf_nodes`に変更。
また、わかりやすくするためにbooleanにしました。
tree, clusterという選択肢を削除しました。

2022-07-20 03:36 UTC, YukikoNoda reviewed
paramsの順番とdescriptionを変更しました。

2022-07-20 03:38 UTC, YukikoNoda reviewed
textのcolor変更が反映されるように変更しました。

2022-07-20 05:07 UTC, YukikoNoda reviewed
`node-space_between`のparamsを追加することで、`fit to area size`が`false`だった場合に、ユーザーが、nodeの並び方向の間隔を調整できるようにしました。

2022-07-20 06:10 UTC, YukikoNoda reviewed
styleの`--togostanza-outline-padding`を削除し、paramsに`graph-padding`を追加しました。
理由は、`graph-fit_to_area_size`がtrueの際にnode circleが見切れることがあるので、paddingで調整を行うためです。
styleで追加したかったのですが、cssのように 複数のpxの値を受け取りたかったので、paramsに追加しました。
styleで行った場合、ワンテンポ遅れて反映されてしまいます。

2022-07-20 09:09 UTC, YukikoNoda reviewed
paramsを使用するものに対して、index.jsにて定義を行いました。

2022-07-21 06:28 UTC, YukikoNoda reviewed
以下の機能を削除しました。
- nodeに対して絶対の大きさでグラフを描画する
- nodeが絶対の大きさの場合にZoomを行うことができる。

これによりgraphはwidth, heightの値に相対して描画されることになります。

paramsは`graph-fit_to_area_size`, `node-space_between`, `node-layer_distance`を削除しました。

2022-07-21 06:46 UTC, YukikoNoda reviewed
以下2点の変更を行いました。
- nodeを閉じた時の色をユーザーが指定できるようにする
- node circleのstrokeを削除

2022-07-21 07:09 UTC, YukikoNoda reviewed
以下の変更を行いました。
- `node-size-min_size` → `node-size-min` に変更。※maxも同様
- node-size-defaultのparamsの削除
- `node-size-min`, `node-size-max` の値を等しくすることで、defaultの半径の大きさを表現
   現在は、node-size-min, node-size-maxの値の平均をdefaultの大きさにしています。

2022-07-21 07:59 UTC, YukikoNoda reviewed
以下の2点を変更しました。
- paramsの`graph-path` → `shape`
- pathのデフォルトカラー

いずれshapeの選択肢に`round`(`radial`)を追加予定です。

2022-07-22 08:16 UTC, YukikoNoda reviewed
以下2点を変更しました。
- paddingのparamsを削除しました。
- 表示エリアを超えている場合でも、グラフを計算・再描画することで、すべての円を表示できるようにできるようにしました。

2022-07-25 01:58 UTC, YukikoNoda reviewed
向きがvertical時のテキストの向きを逆向きにしました。

2022-07-25 04:51 UTC, YukikoNoda reviewed
paddingの変更によって生じるエラー表示の内容を変更しました。

2022-07-25 06:54 UTC, YukikoNoda reviewed
ノードが閉じた時の表示方法を変更しました。

2022-07-26 06:12 UTC, YukikoNoda reviewed
node circleの大きさの指定を半径から直径に変更しました。

2022-07-27 02:25 UTC, YukikoNoda reviewed
colorのgroupを作成しました。
sampleの表示をするために私のGithubにJSONを作成したため、公式用に別のアカウントを使用して作成する必要があります。
コードの確認をお願いします。

JSONの書き方のサンプルとして、READMEを少し変更しました。

2022-07-28 10:41 UTC, YukikoNoda reviewed
円環状のグラフを追加しました。
表示位置がずれているため、padding調整が必要となります。

2022-08-02 03:04 UTC, YukikoNoda reviewed
width,heightから計算しarea内に描画するように変更しました。

2022-08-02 04:40 UTC, YukikoNoda reviewed
jsonファイルを[togostanza-data](https://github.com/togostanza/togostanza-data/blob/main/samples/json/dendrogram-d3.json)に作成し、そのdataを使用することに変更。

2022-08-08 08:56 UTC, YukikoNoda reviewed
color paramsを追加し、ユーザーが色を固定した場合、その色を優先的に使用するように変更しました。colorGroupは2番目に適応されます。

2022-08-12 02:19 UTC, YukikoNoda reviewed
`node-size-data_key`が設定されていない時のpaddingが調整されず見切れてしまう問題を解決しました。

2022-08-15 09:34 UTC, YukikoNoda reviewed
nodeの大きさにより文字が隠れることがあるため、nodeの色の描画方法を4種類に切替可能としました。

2022-08-17 02:57 UTC, YukikoNoda reviewed
scssから線幅設定を削除しました

2022-08-19 07:52 UTC, YukikoNoda reviewed
nodeの開閉時のズレを修正しました。
単純な間違いでした。

8/30の会議までにかかえているDendrogramのtaskはなくなりました。
詳しくは[ClickUp](https://app.clickup.com/t/2t2m4ue)のご確認をお願いいたします。

2022-08-31 06:32 UTC, YukikoNoda reviewed
以下の変更を行いました。
- `Dendrogram-D3`から`Tree-D3`へ名称の変更
- sampleのJSONのファイル名も`tree-d3`に変更
- 色系のparamsを昨日指摘をいただいたとおりに変更(Excelの変更をお願いします。)

2022-08-31 10:03 UTC, YukikoNoda reviewed
以下の変更を行いました。
- param名を`shape` → `layout`に変更
- straight描画方法を削除
- param `graph-direction`を削除

pulldownの項目内容は、`horizontal`、`vertical`、`radial` にしました。

2022-09-01 13:02 UTC, YukikoNoda reviewed
nodeのcircleの上にtextを描画に変更。

2022-09-01 13:06 UTC, YukikoNoda reviewed
params `order-data_key`と`order-sort`を追加することで、以下の順番に並び替えを可能にした。

<入力順>
①順番のkeyないとき
order-data_keyナシ && order-sort: none　　　　　　　


<指定order順>
②順番のkeyがある時(昇順)
order-data_keyアリ && order-sort: ascending

③順番のkeyがある時(降順)
order-data_keyアリ && order-sort: descending　


<abc順>
④abc順(昇順)　　　　
order-data_keyナシ && order-sort: ascending

⑤abc順(降順)
order-data_keyナシ && order-sort: descending　

2022-09-02 02:03 UTC, YukikoNoda reviewed
sort機能の変更を行いました。

パターン

<入力順>
①順番のkeyないとき
order-data_keyナシ　　　　※order-sortが機能しない。


<指定order順>
②順番のkeyがある時(昇順)
order-data_keyアリ && order-sort: ascending

③順番のkeyがある時(降順)
order-data_keyアリ && order-sort: descending　

2022-09-02 02:11 UTC, neznayer approved these changes
ありがとうございます！

2022-09-05 07:42 UTC, YukikoNoda reviewed
radial描画のnodeの開閉時のtextの描画方法を変更しました。
rootとそれ以外のnodeクリックで開閉方法を変更しています。

2022-09-05 11:30 UTC, penqe commented on stanzas/tree-d3/index.js
> +  }
全体の印象
- もっとコメントを多用すべきと思いました。「コメントしなくても理解可能なコード」というアプローチもあるので、必ずしもその限りではありませんが。ただ一般的に、半年後には作者といえどかなり忘れているもので、他者がコードを読むとなると言わんやです。
- この長さだと、関数を活用を検討しても良いでしょう。機能単位に切り分け、特に冒頭で宣言している変数などは、それを必要としている関数の中で宣言させるようにした方が良いでしょう。後々「この変数は果たして要るのだろうか。。？」となることが往々にしてあります。

2022-09-08 07:07 UTC, YukikoNoda commented
主に以下を変更しました。
- コメントを付与し、内容をブロックごとに見やすく変更しました。
- 三項演算子を多用していたものを、switch文で切り替えに変更しました。
- 関数を使用し、コードを短くしました。

2022-09-08 08:56 UTC, YukikoNoda reviewed
以下の変更を行いました。
- 文字列の定数宣言の場所の変更
- `tempGroup` → `maxLabelGroup`
- `MARGIN` → `margin`

2022-09-08 09:47 UTC, merged

2022-09-08 09:48 UTC, penqe commented
ありがとうございました