Vue製table-with-paginaionスタンザの作成
togostanza/metastanza pull request #25
Opened 2021-01-28 04:26 UTC by reika0717

こちらで作業できることあればご指示下さい。お手数ですが、ご確認お願いいたします。

2021-01-28 04:32 UTC, ursm commented
conflict がなく、lint が通っている状態にしていただけますか。わからない点は聞いてください。

2021-01-28 04:34 UTC, reika0717 commented
かしこまりました。

2021-02-03 04:50 UTC, reika0717 commented
Conflictとlintのエラー解決しました。ご確認お願いします。

2021-02-03 05:18 UTC, ursm requested changes
手元でも `npm run lint` と `npm run lint:fix` を実行してみてください

2021-02-03 05:18 UTC, ursm commented on stanzas/table-with-pagination/templates/tbody.html.hbs
> +<tbody>
このファイルはもう使っていないような

2021-02-03 05:18 UTC, ursm commented on stanzas/table-with-pagination/app.vue
> +        perPage: 5  // TODO take from params
これそのままでいいですか？

2021-02-03 05:23 UTC, reika0717 commented on stanzas/table-with-pagination/templates/tbody.html.hbs
> +<tbody>
すみません、削除します。

2021-02-03 05:25 UTC, reika0717 commented on stanzas/table-with-pagination/app.vue
> +        perPage: 5  // TODO take from params
パラメーター化したいところでした…対応します。

2021-02-03 05:30 UTC, ursm commented on stanzas/dev-grouped-barchart/index.js
> +      // title: valueVariable,
ここは lint とは関係なさそうです（元に戻しても通りました）

2021-02-03 05:43 UTC, ursm commented on stanzas/gwas-manhattan-plot/gwas.var2.json2.js
> +export default a_dataset;
こういうケースなら変数に入れずに

``` js
export default {
  foo: 42
};
```

のようにする方が簡潔ですし、ファイルの下の方にデータを弄るコードが隠されている可能性を排除できるので読む人に親切ですね。

ところで、スタンザから json を直接 import できるので、元が json ならそっちの方がよさそうです。

``` js
import foo from "./foo.json";
```

2021-02-03 05:50 UTC, reika0717 commented on stanzas/dev-grouped-barchart/index.js
> +      // title: valueVariable,
恐れ入ります。Duplicateのエラーが出ていたのでコメントアウトしたのですが、場所が違いました。戻しておきます。

2021-02-03 06:08 UTC, reika0717 commented on stanzas/gwas-manhattan-plot/gwas.var2.json2.js
> +export default a_dataset;
有難うございます。そもそもgwas.var2.json2は使ってなさそうなので消してもいいか中嶋に確認中です。
gwas.var2.json.jsの方をご指示いただいた通り、jsonの変換し直接importするように致します。

2021-02-03 06:39 UTC, reika0717 commented on stanzas/table-with-pagination/templates/tbody.html.hbs
> +<tbody>
削除しました。

2021-02-03 06:40 UTC, reika0717 commented on stanzas/table-with-pagination/app.vue
> +        perPage: 5  // TODO take from params
パラメーター化したのですが、ページを移動するとperPageの値が保持されません。
こちらに関してはmasterにマージ後対応しようかと思っております…。

2021-02-03 06:40 UTC, reika0717 commented on stanzas/dev-grouped-barchart/index.js
> +      // title: valueVariable,
戻しました。

2021-02-03 06:40 UTC, reika0717 commented on stanzas/gwas-manhattan-plot/gwas.var2.json2.js
> +export default a_dataset;
ご指示いただいたように修正致しました。

2021-02-03 08:41 UTC, ursm commented on stanzas/gwas-manhattan-plot/gwas.var2.json2.js
> +export default a_dataset;
ありがとうございます。このファイルもいらなくなりますか？

2021-02-03 10:50 UTC, c-nakashima commented on stanzas/gwas-manhattan-plot/gwas.var2.json2.js
> +export default a_dataset;
@ursm @reika0717 諸々ご対応・ご修正ありがとうございます。import/exportも、今後ご教示いただいたように進めてまいります。（gwas.var2.json2の、削除のご対応もありがとうございます。）

2021-02-03 11:06 UTC, reika0717 commented on stanzas/gwas-manhattan-plot/gwas.var2.json2.js
> +export default a_dataset;
@ursm すみません。削除致しました。

2021-02-03 11:33 UTC, ursm approved these changes
ごちゃごちゃとすみません。後でまとめてというのもそれはそれで大変なので、お手数ですが引き続きこんな感じでよろしくお願いします。

一点、データについての補足です。コード中に巨大なデータを含めるとスクリプトの取得に時間が掛かるようになってしまい、終わるまでコードの実行ができなくなってしまう（その間画面が真っ白のままでユーザを戸惑わせる）ため一般的には避けたほうがよいと思います。今は簡単なやり方でよいのですが、今後適切な方法に置き換えていきましょう。

2021-02-03 11:34 UTC, merged

2021-02-03 11:37 UTC, reika0717 commented
とんでもございません…こちらこそお手間を取らせてしまい申し訳ございません。
丁寧にレビューしていただき大変勉強になりました。有難うございます。
巨大なデータについて、かしこまりました。中嶋含め、また相談させて下さい。